# Generated by Django 5.1 on 2024-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/customer/'),
        ),
    ]
