# Generated by Django 5.1 on 2024-08-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_customers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
